kind: Deployment
apiVersion: apps/v1
metadata:
  name: csp-api
spec:
  selector:
    matchLabels:
      app: dotnetcore
      role: backend
  replicas: 1
  template:
    metadata:
      name: csp-api-deployment
      labels:
        app: dotnetcore
        role: backend
        env: develop
    spec:
      containers:
      - name: csp-api
        image: gcr.io/gcr-project/sample:1.0.0
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: api/organiation
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 20
          periodSeconds: 20
          successThreshold: 1
        ports:
        - name: csp-ui-port
          containerPort: 80